---
title: Sage Brown
timezone: UTC
collections:
  homepage:
    title: Homepage
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: gallery
    permalink: "/:title/"
    hero-image:
    images:
- scope:
    path: ''
    type: homepage
  values:
    image:
    link:
title-2: Photgrapher — Portland, Oregon
email: sage.brown@gmail.com
description: Sage Brown, editorial and commercial photographer in Portland, Oregon.
baseurl:
url: http://sagebrown.com
markdown: kramdown
plugins: [jekyll/imgix]
imgix:
  source: sagebrown.imgix.net # Your imgix source address
  secure_url_token: d8C2wxjd8HBZ8FVq # (optional) The Secure URL Token associated with your source
