---
title: Sage Brown
timezone: UTC
collections:
  posts:
    title: Galleries
    output: true
  homepage:
    title: Homepage
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: gallery
    permalink: "/:title/"
    hero-image: 
    images: 
- scope:
    path: ''
    type: homepage
  values:
    image: 
    link: 
title-2: Photgrapher — Portland, Oregon
email: sage.brown@gmail.com
description: Sage Brown, editorial and commercial photographer in Portland, Oregon.
baseurl: ''
url: http://sagebrown.com
markdown: kramdown
